<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18479" started-at="2021-11-25T09:37:57 EET" finished-at="2021-11-25T09:38:16 EET">
    <groups>
    </groups>
    <test name="Rahul Page Tests" duration-ms="12450" started-at="2021-11-25T09:37:57 EET" finished-at="2021-11-25T09:38:10 EET">
      <class name="academy.ConsoleLogsTest">
        <test-method status="PASS" signature="beforeMet()[pri:0, instance:academy.ConsoleLogsTest@4149c063]" name="beforeMet" is-config="true" duration-ms="2656" started-at="2021-11-25T09:37:57 EET" finished-at="2021-11-25T09:38:00 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMet -->
        <test-method status="FAIL" signature="SeleniumDoubleTest()[pri:0, instance:academy.ConsoleLogsTest@4149c063]" name="SeleniumDoubleTest" duration-ms="9520" started-at="2021-11-25T09:38:00 EET" finished-at="2021-11-25T09:38:10 EET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at academy.ConsoleLogsTest.SeleniumDoubleTest(ConsoleLogsTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SeleniumDoubleTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:academy.ConsoleLogsTest@4149c063]" name="quitDriver" is-config="true" duration-ms="74" started-at="2021-11-25T09:38:10 EET" finished-at="2021-11-25T09:38:10 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- academy.ConsoleLogsTest -->
    </test> <!-- Rahul Page Tests -->
    <test name="Home Page Tests" duration-ms="18479" started-at="2021-11-25T09:37:57 EET" finished-at="2021-11-25T09:38:16 EET">
      <class name="academy.HomePageTest">
        <test-method status="PASS" signature="beforeMet()[pri:0, instance:academy.HomePageTest@10289886]" name="beforeMet" is-config="true" duration-ms="2625" started-at="2021-11-25T09:37:57 EET" finished-at="2021-11-25T09:38:00 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMet -->
        <test-method status="PASS" signature="HomePageLogin(java.lang.String,java.lang.String)[pri:0, instance:academy.HomePageTest@10289886]" name="HomePageLogin" duration-ms="9490" started-at="2021-11-25T09:38:00 EET" data-provider="credentials" finished-at="2021-11-25T09:38:10 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@mail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePageLogin -->
        <test-method status="PASS" signature="HomePageLogin(java.lang.String,java.lang.String)[pri:0, instance:academy.HomePageTest@10289886]" name="HomePageLogin" duration-ms="2005" started-at="2021-11-25T09:38:10 EET" data-provider="credentials" finished-at="2021-11-25T09:38:12 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@mail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePageLogin -->
        <test-method status="PASS" signature="checkNavigationBar()[pri:0, instance:academy.HomePageTest@10289886]" name="checkNavigationBar" duration-ms="1158" started-at="2021-11-25T09:38:12 EET" finished-at="2021-11-25T09:38:13 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkNavigationBar -->
        <test-method status="FAIL" signature="checkTitle()[pri:0, instance:academy.HomePageTest@10289886]" name="checkTitle" duration-ms="1085" started-at="2021-11-25T09:38:13 EET" finished-at="2021-11-25T09:38:14 EET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is not correct expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is not correct expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at academy.HomePageTest.checkTitle(HomePageTest.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTitle -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:academy.HomePageTest@10289886]" name="quitDriver" is-config="true" duration-ms="83" started-at="2021-11-25T09:38:16 EET" finished-at="2021-11-25T09:38:16 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- academy.HomePageTest -->
    </test> <!-- Home Page Tests -->
  </suite> <!-- Suite -->
</testng-results>
